notifications:
  email:
    on_success: never
language: cpp
script:
 - mkdir build
 - cd build
 - cmake .. 
 - make -j2
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq bison || /bin/true
 - sudo apt-get install -qq flex || /bin/true
 - sudo apt-get install -qq git || /bin/true
 - sudo apt-get install -qq libgl1-mesa-dev || /bin/true
 - sudo apt-get install -qq libglewmx1.6-dev || /bin/true
